services:
  api-service:
    container_name: api-service
    build: .
    ports:
      - 3000:3000
    environment:
      DB_HOST: ${DB_USERNAME}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}
      APP_PORT: ${APP_PORT}
    depends_on:
      - postgres
    links:
      - postgres

  postgres:
    container_name: postgres
    restart: always
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}